name: HACS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure the repository is valid
        run: |
          curl -fsSL https://hacs.xyz/docs/publish/repository_structure | bash -
